# Generated by Django 6.0.4 on 2026-04-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carManagementSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='images',
            new_name='image',
        ),
    ]
