# Generated by Django 6.0.3 on 2026-03-13 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessCenterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitnessCenterApp.category'),
        ),
    ]
