# Generated by Django 6.0.4 on 2026-05-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeryBakerySystemApp', '0002_alter_baker_user_alter_cake_baker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='baker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cakeryBakerySystemApp.baker'),
        ),
    ]
