# Generated by Django 6.0.4 on 2026-05-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeryBakerySystemApp', '0003_alter_cake_baker'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='picture',
            field=models.ImageField(default='/images/person.png', upload_to=''),
        ),
    ]
